max_sub_array: max_sub_array.cpp
	g++ max_sub_array.cpp -o maxSubFixedWindow -std=gnu++14

run: maxSubFixedWindow
	./maxSubFixedWindow

clean:
	rm -f maxSubFixedWindow

maxSubFixedWindow:
	echo "Hello, World"

